### ISSUE TITLE
unnecessary filter for gnomAD AF

### ISSUE THREAD

**Issue by giorkala** [BRaVa-genetics/SAIGE-annotations-for-BRaVa#1]
I was mistakenly discarding variants with missing gnomAD AF info; these might actually be rare, so we should keep them.

This can be avoided by replacing line 105 with
```
    temp.replace('.', 0, inplace=True)
```
and possibly adding a message later on:
```    
    indx = df1['gnomAD_maxAF'] == 0.0
    print( "Rows with potentially-missing gnomAD AF info: {0} out of {1}.".format(len(indx)-sum(indx), len(indx) ))
```
Not sure if it's worth it a PR, but could do so.
Yiorgos

**Comment by astheeggeggs** [comment]
Code has since been updated to account for this.
