### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by barneyhill** [BRaVa-genetics/SAIGE-annotations-for-BRaVa#2]
Move away from positional headers to explicitly calling user-specified header names. For example there will be a column argument cadd_col="CADD_PHRED" etc.

**Comment by astheeggeggs** [comment]
This is now resolved, with flags to define the set of columns to use in a passed VEP annotated table and the defaults set according to the output of https://github.com/BRaVa-genetics/vep105_loftee (see last code snippet)
